### PR TITLE
SCR team game support

### PR DESCRIPTION
**Pull request by neivv**
Would be nice if someone verified that it works fine for them as well, as there already were more issues than the single one I expected there to be.

### CODE REVIEW

**Comment by 2Pacalypse-** [comment]
I'm not entirely sure about the rules of the team melee games, but the following lobby configuration ends up with Team 2 being eliminated as soon as the game starts. Is that expected? 😃

image

**Comment by neivv** [comment]
Nope, guess something is still broken

**Comment by neivv** [comment]
Wasn't able to reproduce that though - are you sure the game dll was rebuilt?

**Comment by 2Pacalypse-** [comment]
Interestingly enough, the following configuration works without a problem:

image

And so does this one:

image

**Comment by 2Pacalypse-** [comment]
> Wasn't able to reproduce that though - are you sure the game dll was rebuilt?

Yeah, since it works in other cases.

**Comment by neivv** [comment]
Then it seems to be something that's happening randomly :l

**Comment by 2Pacalypse-** [comment]
But it consistently fails with that configuration and works with others I posted.

Also, I went to test this race configuration on battle.net as well, but there when I chose a race for a computer, it selects that race for _all_ computer slots. So it seems impossible to select different races for a computer on battle.net. I assume that's a bug on their system?

And finally, the first race configuration I posted works with 2 human players. It seems to only fail if the second team is made of computers.

**Comment by neivv** [comment]
Huh, that's really weird. Maybe the first computer spawning as random is causing issues then? And maybe it's related to the map as i didn't have issues with FS or regular hunters.

Can you check with 2 humans on the first team and computers on the other?

And 1161 allows selecting different races for the computer team (even if it is pretty pointless as the ai won't be able to take advantage of that), guess blizzard broke it with remastered.

**Comment by neivv** [comment]
Nevermind, 1161 doesn't allow separate races for computers either. And turns out that setting one computer in a team to random but not all causes out-of-bounds memory reads.. Unless the lowest possible slot in ai team is random, which seems to be consistent with what you are seeing.

I probably happened to have the out-of-bounds data that still resulted in valid races or something while doing the first tests.

**Comment by 2Pacalypse-** [comment]
Huh, that's pretty weird. Should we update the UI as well to disallow setting different races to computers then, similar to what SC:R does? Even though _some_ race combinations are valid for a computer, I don't think anyone will really mind not being able to choose them :d

**Review by 2Pacalypse- — APPROVED** [review]

**Pull request merged**
